// Create a user
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Ahmad Fuad I.",
    "email": "dosen1@gmail.com",
    "password": "123456",
    "confPassword": "123456",
    "role": "admin"
}

###
// get All Users
GET http://localhost:5000/users

###
// get Single User
GET http://localhost:5000/users/2883b0d7-4c70-4702-a16f-c9bce775d5fa

###
// Update a user
PATCH http://localhost:5000/users/2883b0d7-4c70-4702-a16f-c9bce775d5fa
Content-Type: application/json

{
    "name": "Muhammad Hafidh A.",
    "email": "mahasiswa2@gmail.com",
    "password": "",
    "confPassword": "",
    "role": "user"
}

###
/// Delete a user
DELETE http://localhost:5000/users/ad15d9fa-1684-464e-a237-82980d88ebad

###
// Login Dosen
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "dosen@gmail.com",
    "password": "123456"
}

###
// Login Mahasiswa
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "mahasiswa1@gmail.com",
    "password": "123456"
}

###
GET http://localhost:5000/me

###
// Logout User
DELETE http://localhost:5000/logout


###
// get All Class
GET http://localhost:5000/classes

###
// POST Data Class
POST http://localhost:5000/classes
Content-Type: application/json

{
    "classname": "Pengembangan dan Penerapan Sistem",
    "description": "Mata kuliah Pengembangan dan Penerapan Sistem bertujuan mengajarkan mahasiswa cara mendefinisikan, mendokumentasikan, dan mengelola kebutuhan perangkat lunak sesuai dengan praktik terbaik industri. Dengan fokus pada pemahaman mendalam terhadap kebutuhan bisnis, mahasiswa akan belajar mengubahnya menjadi dokumentasi yang tepat dan desain perangkat lunak yang sesuai, sambil memahami proses pengelolaan rilis perangkat lunak. Melalui proyek kelompok, mereka akan berlatih menerapkan pengetahuan ini, mempersiapkan mereka untuk menangani tantangan nyata di dunia kerja dan memahami penelitian terkini dalam pengembangan dan penerapan sistem.",
    "visibility": "show"
}

###
// get All Questions
GET http://localhost:5000/questions

###
// get All Questions
GET http://localhost:5000/questions

###
// POST Data Question
POST http://localhost:5000/questions
Content-Type: application/json

{
    "question_text": "question_text",
    "topic": "topic",
    "difficulty": "difficulty",
    "answer_text_1": "answer_text_1",
    "answer_text_2": "answer_text_2",
    "answer_text_3": "answer_text_3",
    "answer_text_4": "answer_text_4",
    "answer_text_5": "answer_text_5"
}


###
// get Single Question
GET http://localhost:5000/questions/e2ad1a0a-0131-41ac-a70c-4777e24e2dfd

###
// Delete Data Question
DELETE http://localhost:5000/questions/e2ad1a0a-0131-41ac-a70c-4777e24e2dfd